Changed Modernizr.load to $.getScript
adaptlearning/adapt-contrib-media pull request #177
Opened 2018-01-31 18:05 UTC by jose-campos-sr

Modernizr.load has been deprecated resulting on a error when using the media component to display a Vimeo video. Fixed by changing Modernizr.load for $.getScript.

2018-01-31 18:08 UTC, moloko commented
thanks, I presume this was as a result of us updating to the latest Modernizr?

you might as well remove the old code completely not leave it commented out

2018-01-31 18:10 UTC, jose-campos-sr commented
Correct, just pushed the updated version with no commented code.

2018-02-01 13:25 UTC, moloko commented
issue: https://github.com/adaptlearning/adapt_framework/issues/1950

2018-02-01 13:37 UTC, moloko requested changes
thanks for this, fixes the issue for me. just a few housekeeping/style issues to resolve if you would be so kind?

2018-02-01 13:37 UTC, moloko commented on js/adapt-contrib-media.js
> +                    	.done(function() {
could you just sort the indentation out in lines 151 - 153? you've used tabs for indentation here - but the rest of the file uses spaces

2018-02-01 13:37 UTC, moloko commented on js/adapt-contrib-media.js
> +	                    .fail(function(){
for consistency, would you mind adding a space between `()` and `{`?

2018-02-01 21:07 UTC, jose-campos-sr commented
Done.

2018-02-01 21:13 UTC, moloko approved these changes
lovely, thanks very much!

2018-02-02 05:02 UTC, chetan-hajare approved these changes

2018-02-05 11:19 UTC, oliverfoster commented
This also works now:
```js
Adapt.loadScript("url", callback);
```

2018-02-05 11:19 UTC, oliverfoster approved these changes

2018-02-05 12:46 UTC, merged