Converted js to es6 classes
adaptlearning/adapt-contrib-media pull request #214
Opened 2021-03-09 09:53 UTC by eleanor-heath

Linked issue https://github.com/adaptlearning/adapt_framework/issues/2808

2021-03-09 10:20 UTC, cahirodoherty-learningpool approved these changes
👀

2021-03-09 13:25 UTC, oliverfoster requested changes

2021-03-09 13:25 UTC, oliverfoster commented on js/adapt-contrib-media.js
> +      this.froogaloopAdded = false;
The variable `froogaloopAdded` is defined in the module because its behaviour should only happen once, only when the first vimeo video is added and not on every component render.

2021-03-09 13:25 UTC, oliverfoster commented on js/adapt-contrib-media.js
> +    defaultSeekBackwardInterval: (duration) => {
```suggestion
    defaultSeekBackwardInterval: duration => {
```
Brackets are unnecessary. 

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#comparing_traditional_functions_to_arrow_functions

2021-03-09 13:25 UTC, oliverfoster commented on js/adapt-contrib-media.js
>            $.getScript('assets/froogaloop.js')
You can see here `froogaloop` is imported globally, so this should only be done once globally.

2021-03-09 13:25 UTC, oliverfoster commented on js/adapt-contrib-media.js
>        ComponentView.prototype.remove.call(this);
```suggestion
      super.remove();
```

2021-03-09 13:25 UTC, oliverfoster commented on js/adapt-contrib-media.js
>    return Adapt.register('media', {
This stuff should be in the main file, and the view should be in a view file.

2021-03-09 15:25 UTC, eleanor-heath commented
@oliverfoster can you take another look when you have a chance please.

2021-03-09 15:32 UTC, oliverfoster requested changes

2021-03-09 15:32 UTC, oliverfoster commented on js/adapt-contrib-media.js
>    'libraries/mediaelement-and-player',
The libraries are only needed in the view.

2021-03-09 15:32 UTC, oliverfoster commented on js/mediaView.js
> +  _.extend(window.mejs.MepDefaults, {
All `_.extend` can become `Object.assign`

2021-03-09 15:32 UTC, oliverfoster commented on js/mediaView.js
> +      const classes = ComponentView.prototype.className.call(this);
```suggestion
      const classes = super.className();
```

2021-03-09 15:32 UTC, oliverfoster commented on js/mediaView.js
> +      this.addThirdPartyFixes(modelOptions, function createPlayer() {
Fat arrow

2021-03-09 15:32 UTC, oliverfoster commented on js/mediaView.js
> +  };
No semi colon required

2021-03-09 15:50 UTC, oliverfoster approved these changes

2021-03-10 12:29 UTC, moloko commented
re: 71ae9c7 you don't actually need the trailing whitespace in all those instances - it's only needed where you need to force a line break - see https://www.markdownguide.org/basic-syntax/#line-breaks

for example, you don't need to have two spaces on a line that's set up as a heading

(no need to change this PR, it's more just FYI for future README amends)

2021-03-10 14:11 UTC, moloko requested changes
a few eslint fixes plus some other suggestions

2021-03-10 14:11 UTC, moloko commented on js/mediaView.js
> +      if (_.findWhere(this.model.get('_media').cc, { srclang: lang })) return lang;
there is an opportunity to switch from `_.findWhere` to vanilla js here... but whether it's really worth it or not is questionable..! I think we should probably leave as-is but if anyone else feels differently, make your case...

2021-03-10 14:11 UTC, moloko commented on js/mediaView.js
> +              console.log('Could not load froogaloop.js');
```suggestion
              Adapt.log.error('Could not load froogaloop.js');
```

2021-03-10 14:11 UTC, moloko commented on js/mediaView.js
> +      });
```suggestion
      this.model.set({
        _isMediaEnded: false,
        _isMediaPlaying: false
      });
```

2021-03-10 14:11 UTC, moloko commented on js/mediaView.js
> +      this.onMediaElementClick = this.onMediaElementClick.bind(this);
we could just add 'onOverlayClick' and 'onMediaElementClick' to the `_.bindAll` on line 78 then dispense with these two lines

2021-03-10 14:11 UTC, moloko commented on js/mediaView.js
> +        this.$('.media__transcript-btn').a11y_focus();
Change to new a11y API, I think it should be:
```suggestion
        Adapt.a11y.focus(this.$('.media__transcript-btn'));
```

2021-03-10 15:52 UTC, moloko approved these changes
Looks good to me. Gave it a quick test in IE11, FF & Chrome.

2021-03-12 16:52 UTC, moloko commented
@oliverfoster do you want to re-review or are you happy with this?

2021-03-15 12:05 UTC, oliverfoster approved these changes

2021-03-15 12:16 UTC, cahirodoherty-learningpool approved these changes
👀

2021-03-15 12:55 UTC, merged