issue/#231 - Add region role to video container
adaptlearning/adapt-contrib-media pull request #233
Opened 2022-05-17 22:15 UTC by joe-replin

#231 Assigns the media container a role of 'region' instead of 'application'. Also uses the title and displayTitle as a label for aria context when learners focus on the media container.

2022-05-23 09:38 UTC, cahirodoherty-learningpool approved these changes
👀

2022-05-23 11:35 UTC, oliverfoster commented
Have you tested with Jaws and NVDA @joe-replin ?

2022-05-24 10:09 UTC, oliverfoster requested changes

2022-05-24 10:09 UTC, oliverfoster commented on js/mediaView.js
> +    const containerLabel = this.model.get('displayTitle') ? this.model.get('displayTitle') : this.model.get('title');
```suggestion
    const containerLabel = this.model.get('displayTitle') || this.model.get('title');
```

2022-05-24 10:09 UTC, oliverfoster commented on js/mediaView.js
> +    const containerLabel = this.model.get('displayTitle') ? this.model.get('displayTitle') : this.model.get('title');
I'm not sure if this container label needs to be defined aside from the displayTitle and title as well.

2022-05-24 14:16 UTC, joe-replin commented on js/mediaView.js
> +    const containerLabel = this.model.get('displayTitle') ? this.model.get('displayTitle') : this.model.get('title');
I was asked to include a meaningful label alongside the role. Something similar was suggested for the MCQ/GMCQ components for reminding learners of the context for the region while focusing: https://github.com/adaptlearning/adapt-contrib-mcq/issues/177

2022-05-24 22:36 UTC, oliverfoster approved these changes

2022-05-27 14:01 UTC, eleanor-heath commented on js/mediaView.js
> +    this.$('.mejs-container').attr('role', 'region');
dont think this line is needed because the role attribute is set on the element with class mejs-container below

2022-05-27 14:04 UTC, eleanor-heath approved these changes

2022-06-13 14:00 UTC, joe-replin commented
Done. Thank you, @eleanor-heath!

2022-06-13 14:02 UTC, merged