Update: Adjusts transcript triggers (fixes #283)
adaptlearning/adapt-contrib-media pull request #284
Opened 2024-02-08 18:53 UTC by joe-replin

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Update
* Adds new trigger to capture transcript toggles
* Adjusts transcript completion so it only triggers when it completes the component
* fixes #283

2024-02-09 14:43 UTC, danielghost requested changes

2024-02-09 14:43 UTC, danielghost commented on js/mediaView.js
> +      Adapt.trigger(media:transcriptComplete, this);
The event name needs to be a string if being used this way:
```JavaScript
Adapt.trigger(`media:${transcriptComplete}`, this);
```

Not sure the logic makes sense though anyway as it will only ever trigger 'media:transcriptComplete' via this condition. Am assuming this should have just been `Adapt.trigger('media:transcriptComplete', this);`?

2024-02-09 14:43 UTC, danielghost commented on js/mediaView.js
> +    }
Can this method be simplified to the following without impact?
```JavaScript
transcriptTriggers() {
  const setCompletionOnView = this.model.get('_transcript')._setCompletionOnView;
  const isComplete = this.model.get('_isComplete');
  Adapt.trigger('media:transcript', this);
  if (setCompletionOnView && !isComplete) {
    Adapt.trigger('media:transcriptComplete', this);
    this.setCompletionStatus();
  }
}
```

2024-02-09 14:43 UTC, danielghost commented on js/mediaView.js
>      if (this.model.get('_transcript')._setCompletionOnView === false) return;
Yes this need to be removed otherwise it will only trigger if `_setCompletionOnView: true`.

2024-02-09 15:15 UTC, oliverfoster commented on js/mediaView.js
> +    }
You can reduce nesting and increase readability by doing this:
```JavaScript
transcriptTriggers() {
  const setCompletionOnView = this.model.get('_transcript')._setCompletionOnView;
  const isComplete = this.model.get('_isComplete');
  const shouldComplete = (setCompletionOnView && !isComplete);
  Adapt.trigger('media:transcript', this);
  if (!shouldComplete) return;
  this.setCompletionStatus();
  Adapt.trigger('media:transcriptComplete', this);
}
```

2024-02-12 19:03 UTC, joe-replin commented on js/mediaView.js
> +    this.transcriptTriggers();
I weighed both sides together and leaned this way.ith other media UI such as volume or speed. At a high-level, these triggers are collecting click rates.
1. If tracking only the on open toggle, it's probably better to restrict that in an alternate plug-in based on your needs.
2. I was also keeping inline with how the plugin simply triggers clicks in other media UI such as volume & speed.

2024-03-01 16:42 UTC, danielghost requested changes

2024-03-01 16:42 UTC, danielghost commented on js/mediaView.js
> +    this.transcriptTriggers();
In that case, can it be amended to include the transcript state with the trigger?

2024-04-08 11:40 UTC, oliverfoster commented on js/mediaView.js
> +    Adapt.trigger('media:transcriptComplete', state, this);
```suggestion
    Adapt.trigger('media:transcript', state, this);
    Adapt.trigger('media:transcript', 'complete', this);
```

There seems no point having a separate event now that there's a state component.

2024-05-24 09:27 UTC, oliverfoster approved these changes

2024-05-29 21:55 UTC, swashbuck approved these changes
👍

2024-06-11 08:28 UTC, oliverfoster commented
@cahirodoherty-learningpool would you mind rechecking this please?

2024-06-11 09:59 UTC, cahirodoherty-learningpool approved these changes
👀

2024-06-11 10:02 UTC, merged