Breaking: Upgrade MediaElement.js to 7.0.7 (fixes #298 #297 #232)
adaptlearning/adapt-contrib-media pull request #299
Opened 2024-08-14 21:21 UTC by swashbuck

Fix #298 #297 #232

### Dependencies
* **Requires** Vanilla theme updates from https://github.com/adaptlearning/adapt-contrib-vanilla/pull/524. The exact Vanilla version is TBD, but we should probably add it to the readme.
* **Requires** Framework version [5.42.7](https://github.com/adaptlearning/adapt_framework/releases/tag/v5.42.7) / Core [6.60.8](https://github.com/adaptlearning/adapt-contrib-core/releases/tag/v6.60.8) for usage of `.visually-hidden-focusable` #324

### Breaking
* Upgrades MediaElement.js from v2.21.2 to [v7.0.7](https://github.com/mediaelement/mediaelement/releases/tag/7.0.7). This includes breaking [namespace changes](https://github.com/mediaelement/mediaelement/blob/master/MIGRATION.md#migrating-from-2x-to-4x-version).
* Removes Flash [support](https://github.com/mediaelement/mediaelement/blob/master/MIGRATION.md#migrating-from-6x-to-7x-version)
* Removes IE 9/10 [support](https://github.com/mediaelement/mediaelement/blob/master/MIGRATION.md#changes-on-420-version)
* Removes Vimeo support (Vimeo-specific styles and JS shims). Anyone who needs Vimeo support should migrate to the Adapt [Vimeo plugin](https://github.com/adaptlearning/adapt-vimeo).
* Removes YouTube support. Anyone who needs YouTube support should migrate to the Adapt [YouTube plugin](https://github.com/adaptlearning/adapt-youtube).

### Notable changes and deletions
* First off, refer to the MediaElement [migration notes](https://github.com/mediaelement/mediaelement/blob/master/MIGRATION.md#migrating-from-2x-to-4x-version), particularly regarding the [namespace changes](https://github.com/mediaelement/mediaelement/blob/master/MIGRATION.md#migrating-from-2x-to-4x-version).
* `speed`, `jumpforward` and `skipback` have moved to mejs plugins. Other [plugins](https://github.com/mediaelement/mediaelement-plugins/tree/master?tab=readme-ov-file#available-plugins) can be considered for inclusion in the future.
* The `MediaFeatures` object is now just `Features`
* MediaElement success callback passes different parameters: `media`, `node`, and `instance`. I've added documentation about this to `onPlayerReady()` which is the success callback function.
* Some properties have moved. `mediaElement.player` changed to `mediaElement.options`. `selectedTrack` has moved to the `instance` object mentioned above.
* Removed many assets. Icon implementation by default now uses SVG [symbols](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol). When using the Vanilla theme (PR listed below), these icons are replaced with Vanilla font icons.
* Added a README.md to the libraries directory detailing the changes we've directly made to the mejs library itself. These changes have pending PRs at the mejs GitHub repo.

### Fix
* #297 
* #232 

### Configuration changes to existing courses
None

### Regression testing
The following fixes could use retesting. I could not find the original GitHub tickets for some of these.

1. "**Default shortcut keys trap a screen reader user** inside the player once in focus. These keys are unnecessary as one may traverse the player in a linear fashion without needing to know or use shortcut keys. Below is the removal of the default shortcut keys." The fix I've implemented is slightly different from the [old fix](https://github.com/adaptlearning/adapt-contrib-media/blob/7fb7d7ef6ee5762e130f7e672baf1bff7c45704c/js/mediaLibrariesOverrides.js#L3).
2. Removed: "The **default seek interval functions** are passed two different data types from mejs which they handle incorrectly. One is a duration integer the other is the player object. The default functions error on slider key press and so break accessibility." The [old fix](https://github.com/adaptlearning/adapt-contrib-media/blob/7fb7d7ef6ee5762e130f7e672baf1bff7c45704c/js/mediaLibrariesOverrides.js#L3) rewrites the defaultSeekForwardInterval and defaultSeekBackwardInterval  functions to check the type of the input. These two functions have been slightly rewritten in the newer mejs library, so a fix may no longer be needed. I have removed the previous fix for now.
3. Removed [**setupPlayPauseToggle()**](https://github.com/adaptlearning/adapt-contrib-media/blob/7fb7d7ef6ee5762e130f7e672baf1bff7c45704c/js/mediaView.js#L333) fix: "Overrides the default play/pause functionality to stop accidental playing on touch devices... we don't have a this.mediaElement.player ref on iOS devices." The fix seemed to actually break play/pause functionality on iOS, so I've removed it.
4. Removed [**buildfullscreen()**](https://github.com/adaptlearning/adapt-contrib-media/blob/7fb7d7ef6ee5762e130f7e672baf1bff7c45704c/js/mediaLibrariesOverrides.js#L60) override ("Overwrite mediaelement-and-player buildfullscreen to remove global delete"). The only significant difference in the current override was to remove two `delete hideTimeout` lines. The new `buildfullscreen()` in `mediaelement-and-player.js` does not use this.
5. Removed [**killContextMenuTimer**](https://github.com/adaptlearning/adapt-contrib-media/blob/7fb7d7ef6ee5762e130f7e672baf1bff7c45704c/js/mediaLibrariesOverrides.js#L46) override to "remove global delete" since it no longer exists in mejs
6. Removed CSS [fix]() for https://github.com/adaptlearning/adapt_framework/issues/1883
7. Removed CSS [fix](https://github.com/adaptlearning/adapt-contrib-media/blob/7fb7d7ef6ee5762e130f7e672baf1bff7c45704c/less/mep-overrides.less#L16) for "touch devices to override standard hover event in mep.less L119"
8. Removed CSS [fix](https://github.com/adaptlearning/adapt-contrib-media/blob/7fb7d7ef6ee5762e130f7e672baf1bff7c45704c/less/mep-overrides.less#L79C4-L79C58) for "missing control icons on iOS touch devices"
9. Removed CSS [fix](https://github.com/adaptlearning/adapt-contrib-media/blob/7fb7d7ef6ee5762e130f7e672baf1bff7c45704c/less/mep-overrides.less#L4C6-L5C87) for "The width set by mejs is always 100% of container, set in pixels. Having a fixed pixel size prevents iOS from changing orientation without scaling."
10. Fix for firefox fullscreen api #239 The fix for this PR was recent, so it should still be fine.

### Known issues
* #304

2024-10-30 17:05 UTC, simondate commented
I've noticed that Youtube isn't working either - The README does mention support is temperamental, but perhaps this should be properly documented as being removed like it is with Vimeo.

2024-10-30 17:11 UTC, swashbuck commented
> I've noticed that Youtube isn't working either - The README does mention support is temperamental, but perhaps this should be properly documented as being removed like it is with Vimeo.

Thanks, @simondate . I've added this to the PR notes above.

2024-12-11 14:39 UTC, swashbuck commented
Ready for review.

2024-12-17 11:29 UTC, lemmyadams approved these changes

2025-01-06 17:32 UTC, oliverfoster commented
On any existing course, when updating adapt-contrib-media, **without** also including the vanilla pull request [#524](https://github.com/adaptlearning/adapt-contrib-vanilla/pull/524), the media element will not be styled, it will look as the default mejs styling:
![image](https://github.com/user-attachments/assets/f28b3a5d-4fd2-4e77-9ec3-be9fba741bc5)

Once the file changes from the vanilla pull request are included, mep.less and mep-legacy.less, it should look like this:
![image](https://github.com/user-attachments/assets/9f7a5b88-5182-4402-bec8-3c52014f4d0b)

New courses with this and the vanilla pr will be styled as above and expected.

2025-01-06 17:33 UTC, oliverfoster commented
Further bug fixes: https://github.com/adaptlearning/adapt-contrib-media/pull/311

2025-03-20 07:40 UTC, oliverfoster commented
None of these files need executable permissions because none of them are executable. What are the last commits trying to fix?

2025-03-20 14:18 UTC, swashbuck commented
> None of these files need executable permissions because none of them are executable. What are the last commits trying to fix?

I was reverting the change made in this PR to get the file permissions back to where they were previously. For example, [adapt-contrib-media.js](https://github.com/adaptlearning/adapt-contrib-media/blob/master/js/adapt-contrib-media.js) is currently executable. I didn't want to add any additional files to this already overstuffed PR. Happy to change it, though?

<img width="534" alt="Screenshot 2025-03-20 at 8 18 06 AM" src="https://github.com/user-attachments/assets/b2d3a509-b902-4d49-8b2a-437fcfe03996" />

2025-03-25 21:25 UTC, swashbuck commented
**Bug:** 🐞 Need to fix an issue in Chrome. The closed captions are not showing when in fullscreen mode. Firefox seems fine. Testing on a Mac.

2025-03-28 16:48 UTC, swashbuck commented
> **Bug:** 🐞 Need to fix an issue in Chrome. The closed captions are not showing when in fullscreen mode. Firefox seems fine. Testing on a Mac. Need to see if this is a bug with the ME.js library.

Fixed by https://github.com/adaptlearning/adapt-contrib-vanilla/pull/524/commits/2188c7d3691f9702e23bc803d777395bcb468f10

2025-05-14 09:50 UTC, oliverfoster commented
Is this ready for review? @swashbuck

2025-05-14 14:27 UTC, swashbuck commented
> Is this ready for review? @swashbuck

It is, aside from any new issues we find.

2025-05-15 10:15 UTC, oliverfoster requested changes
We should probably remove `transcript.pdf` from the `assets/` folder to prevent it from being unnecessarily distributed with every course containing this plugin. It can be moved to `adapt_framework`.

2025-05-15 10:15 UTC, oliverfoster commented on js/mediaView.js
> +      if (!_media.mp3 && !_media.mp4 && !_media.ogv && !_media.webm && !_media.source) {
Probably need similar if someone tries to use youtube or vimeo.

2025-05-15 10:15 UTC, oliverfoster commented on templates/media.hbs
> +        {{else equals _aspectRatio "portrait"}} width="540" height="960"{{/equals}}
Was there a reason for removing the default landscape sizing?

2025-05-21 15:17 UTC, joe-allen-89 reviewed
Testing using NVDA and latest Firefox/Chrome, couple of issues, but looking really good overall
- You can navigate through the 'mejs__captions-selector' when it's not visible
- On chrome there's a weird bug that if you open captions and select none, you can't use the arrows to navigate away
- When navigating through the selector it highlights an invisible checkbox with 'radio button not checked', then jumps to the text which doesn't include if it's selected
- Skip to transcript button missing in firefox (works as expected in Chrome)
- When exiting fullscreen, the screenreader jumps to the top of the page (this was also an issue with latest media release)

2025-06-09 18:57 UTC, swashbuck commented
> 🪲 **New bug** Found an issue where backwards scrubbing is broken #323 Should fix _or_ revert this before release.

I've reverted part of the #320 fix. Backwards scrubbing is now possible when preventing forward scrubbing.

2025-06-09 19:34 UTC, oliverfoster commented on libraries/README.md
> +## mediaelement-and-player.js
Could you do a permalink to a version or commit or tag instead of the current matter branch?

2025-06-09 19:38 UTC, oliverfoster commented
@joe-allen-89 

> When exiting fullscreen, the screenreader jumps to the top of the page (this was also an issue with latest media release)

@danielghost has a core fix for this hopefully

2025-06-09 19:51 UTC, swashbuck commented on libraries/README.md
> +## mediaelement-and-player.js
Done in [2cc67fd](https://github.com/adaptlearning/adapt-contrib-media/pull/299/commits/2cc67fd56c69f29276b1e46b3bc30c36908dd013)

2025-06-09 21:19 UTC, swashbuck commented on templates/media.hbs
> +        {{else equals _aspectRatio "portrait"}} width="540" height="960"{{/equals}}
Ok, I've set this up to _not_ set a size when using native controls. Could use some help with Android testing, though.

2025-06-10 13:23 UTC, oliverfoster commented on templates/media.hbs
> +        {{else equals _aspectRatio "portrait"}} width="540" height="960"{{/equals}}
What do you need?

2025-06-10 13:41 UTC, swashbuck commented on templates/media.hbs
> +        {{else equals _aspectRatio "portrait"}} width="540" height="960"{{/equals}}
Testing on an Android device with `AndroidUseNativeControls` set to true and false

2025-06-10 21:50 UTC, swashbuck commented
> Skip to transcript button missing in firefox (works as expected in Chrome)

@joe-allen-89 Will you retest this? Should be fixed now.

2025-06-11 10:02 UTC, oliverfoster commented on templates/media.hbs
> +        {{else equals _aspectRatio "portrait"}} width="540" height="960"{{/equals}}
Both the players are working fine on Pixel 7, Chrome 138.0.7151.72 Android 15

2025-06-11 10:04 UTC, oliverfoster commented
![image](https://github.com/user-attachments/assets/2da8b425-49e8-45cb-901c-dfbc89894332)

Firefox skip to transcript working here.

2025-06-11 20:09 UTC, oliverfoster approved these changes

2025-07-28 09:15 UTC, cahirodoherty-learningpool approved these changes
👀

2025-07-28 13:47 UTC, merged